# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('p4-example', ['ns4', 'csma', 'internet', 'applications', 'internet-apps'])
    obj.source = ['p4-example.cc']
